version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST_ISOLATION=false
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
      - N8N_EXTRA_HOSTS=host.docker.internal:host-gateway
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network

volumes:
  n8n_data:

networks:
  n8n_network:
    driver: bridge 